@FluentOrdersValidation_HostAddress = https://localhost:7004

POST {{FluentOrdersValidation_HostAddress}}/api/customer
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "order": {
    "orderDate": "2024-12-26T10:00:00",
    "products": [
      { "name": "Laptop", "price": 1200 },
      { "name": "", "price": -5 }
    ]
  }
}

###
